### ISSUE TITLE
Fragments with different fields

### ISSUE THREAD

**Issue by nelhop** [markhuot/craftql#235]
I would like to query a list of appointments which can have three different entry types (Lecture, Date_group, Date_other). The queries below only work if every fragment has the same fields.

For example in `query datesList` I don't need `dates_date_end` and `dates_date_allday` on `Lecure` but I have to include them in the query (and in craft) to avoid an error.

```graphql
query datesList($limit: Int = 100, $timefilter: String){
  datesList: entries (
    section:[dates],
    dates_date_start: $timefilter,
    limit: $limit,
    orderBy: "dates_date_start ASC",
    ) {
      __typename
      id
      title
    ... on DatesLecture {
      dates_date_start
      dates_location
      dates_teaser
      dates_date_end # unnessesary
      dates_date_allday # unnessesary
      dates_image {url(transform: termineListe)}
    }
    ... on DatesDate_group {
      dates_date_start
      dates_date_end
      dates_date_allday
      dates_location
      dates_teaser
      dates_image {url(transform: termineListe)}
      # dates_category_group { id, title }
    }
    ...on DatesDate_other {
      dates_date_start
      dates_date_end
      dates_date_allday
      dates_location
      dates_teaser
      dates_image {url(transform: termineListe)}
      # dates_categorie_other { id, title }
    }
  }
}
```

Also I would like to query `dates_category_group` in `query dateItem`, which is only a field of `Date_group` and `Date_other` but not of `Lecture`.

```graphql
query dateItem( $datesId: [Int] ){
  dateItem: entry ( id: $datesId ) {
    __typename
    id
    title
    ... on DatesLecture {
      dates_date_start
      dates_location
      dates_teaser
      dates_image {url(transform: termineListe)}
    }
    ... on DatesDate_group {
      dates_date_start
      dates_date_end
      dates_date_allday
      dates_location
      dates_teaser
      dates_image {url(transform: termineListe)}
      # dates_category_group { id, title }
      # dates_text { content }
    }
    ...on DatesDate_other {
      dates_date_start
      dates_date_end
      dates_date_allday
      dates_location
      dates_teaser
      dates_image {url(transform: termineListe)}
      # dates_categorie_other { id, title }
      # dates_text { content }
    }
  }
}
```

Oddly the error does not appear in the CraftQL Interface but only in the frontend (apollo-nuxt).
```console
ERROR  Cannot read property 'datesList' of null
  at app.apolloProvider.defaultClient.query.then.datesList (pages/termine/index.js:380:35)
  at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by nelhop** [comment]
Figures out to get this to work the schema needs to be populated correctly.
See: https://cmty.app/nuxt/apollo-module/issues/c51#comment-5c6c610336f69c7be4e7892f

**Comment by markhuot** [comment]
FYI, not sure if it helps here but you have access to the following CLI command that will print fragment types to std out. Redirect it to a `.json` and then you can load it in to Apollo,

```
$ ./craft craftql/tools/fetch-fragment-types
```

also,

```
$ ./craft craftql/tools/fetch-fragment-types > fragments.json
```
