### ISSUE TITLE
Plugin breaks CLI

### ISSUE THREAD

**Issue by jan-thoma** [markhuot/craftql#246]
Craft 3.1.18
CraftQL 1.3.1

If i try ./craft help i get this error returned:

```
Exception 'yii\base\InvalidArgumentException' with message 'Invalid path alias: @craftQlPluginHelper/controllers'

in /var/www/webroot/ROOT/startsummit/vendor/yiisoft/yii2/BaseYii.php:154

Stack trace:
#0 /var/www/webroot/ROOT/startsummit/vendor/yiisoft/yii2/base/Module.php(257): yii\BaseYii::getAlias('@craftQlPluginH...')
#1 /var/www/webroot/ROOT/startsummit/vendor/yiisoft/yii2/console/controllers/HelpController.php(246): yii\base\Module->getControllerPath()
#2 /var/www/webroot/ROOT/startsummit/vendor/yiisoft/yii2/console/controllers/HelpController.php(241): yii\console\controllers\HelpController->getModuleCommands(Object(craftQlPluginHelper\Module))
#3 /var/www/webroot/ROOT/startsummit/vendor/yiisoft/yii2/console/controllers/HelpController.php(175): yii\console\controllers\HelpController->getModuleCommands(Object(craft\console\Application))
#4 /var/www/webroot/ROOT/startsummit/vendor/yiisoft/yii2/console/controllers/HelpController.php(187): yii\console\controllers\HelpController->getCommands()
#5 /var/www/webroot/ROOT/startsummit/vendor/yiisoft/yii2/console/controllers/HelpController.php(293): yii\console\controllers\HelpController->getCommandDescriptions()
#6 /var/www/webroot/ROOT/startsummit/vendor/yiisoft/yii2/console/controllers/HelpController.php(67): yii\console\controllers\HelpController->getDefaultHelp()
#7 [internal function]: yii\console\controllers\HelpController->actionIndex(NULL)
#8 /var/www/webroot/ROOT/startsummit/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /var/www/webroot/ROOT/startsummit/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#10 /var/www/webroot/ROOT/startsummit/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('', Array)
#11 /var/www/webroot/ROOT/startsummit/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('', Array)
#12 /var/www/webroot/ROOT/startsummit/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('help', Array)
#13 /var/www/webroot/ROOT/startsummit/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('help', Array)
#14 /var/www/webroot/ROOT/startsummit/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('help', Array)
#15 /var/www/webroot/ROOT/startsummit/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#16 /var/www/webroot/ROOT/startsummit/craft(22): yii\base\Application->run()
#17 {main}
```

**Comment by jan-thoma** [comment]
Sorry, this error was caused by acustom module and is not related to the plugin

**Comment by davorpeic** [comment]
@jan-thoma Please close this issue. 10x
