### ISSUE TITLE
'must be of the type integer' error

### ISSUE THREAD

**Issue by lukeholder** [markhuot/craftql#29]
Craft 3 RC1 

Need to check field layout ID is not null before calling craft\services\Fields::getLayoutById() in line 32 of craftql/src/Services/FieldService.php

Good practice to check for `null` before passing to any Craft 3 `->*getById()` since all params are now type hinted as `int`.

```
craft\services\Fields::getLayoutById() must be of the type integer, null given, called in /Users/luke/Code/Projects/Craft3/craftql/src/Services/FieldService.php on line 32 and defined in /Users/luke/Code/Projects/Craft3/cms/src/services/Fields.php:949
Stack trace:
#0 /Users/luke/Code/Projects/Craft3/craftql/src/Services/FieldService.php(32): craft\services\Fields-&gt;getLayoutById(NULL)
#1 /Users/luke/Code/Projects/Craft3/craftql/src/Types/Volume.php(22): markhuot\CraftQL\Services\FieldService-&gt;getFields(NULL, Object(markhuot\CraftQL\Request))
#2 /Users/luke/Code/Projects/Craft3/craftql/src/Factories/Volume.php(11): markhuot\CraftQL\Types\Volume-&gt;__construct(Object(craft\volumes\Local), Object(markhuot\CraftQL\Request))
#3 /Users/luke/Code/Projects/Craft3/craftql/src/Factories/BaseFactory.php(34): markhuot\CraftQL\Factories\Volume-&gt;make(Object(craft\volumes\Local), Object(markhuot\CraftQL\Request))
#4 /Users/luke/Code/Projects/Craft3/craftql/src/Factories/BaseFactory.php(44): markhuot\CraftQL\Factories\BaseFactory-&gt;get(&#039;5&#039;, &#039;query&#039;)
#5 /Users/luke/Code/Projects/Craft3/craftql/src/Services/GraphQLService.php(63): markhuot\CraftQL\Factories\BaseFactory-&gt;all()
#6 /Users/luke/Code/Projects/Craft3/craftql/src/Controllers/ApiController.php(93): markhuot\CraftQL\Services\GraphQLService-&gt;getSchema(Object(markhuot\CraftQL\Models\Token))
#7 [internal function]: markhuot\CraftQL\Controllers\ApiController-&gt;actionIndex()
#8 /Users/luke/Code/Projects/Craft3/craft3.craft.dev/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /Users/luke/Code/Projects/Craft3/craft3.craft.dev/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction-&gt;runWithParams(Array)
#10 /Users/luke/Code/Projects/Craft3/craft3.craft.dev/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller-&gt;runAction(&#039;index&#039;, Array)
#11 /Users/luke/Code/Projects/Craft3/cms/src/web/Application.php(242): yii\base\Module-&gt;runAction(&#039;craftql/api/ind...&#039;, Array)
#12 /Users/luke/Code/Projects/Craft3/craft3.craft.dev/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application-&gt;runAction(&#039;craftql/api/ind...&#039;, Array)
#13 /Users/luke/Code/Projects/Craft3/cms/src/web/Application.php(207): yii\web\Application-&gt;handleRequest(Object(craft\web\Request))
#14 /Users/luke/Code/Projects/Craft3/craft3.craft.dev/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application-&gt;handleRequest(Object(craft\web\Request))
#15 /Users/luke/Code/Projects/Craft3/craft3.craft.dev/web/index.php(21): yii\base\Application-&gt;run()
#16 {main}</textarea>
```

**Comment by markhuot** [comment]
Thanks Luke, I’ll make this change.

Curious, though… how do you end up with a null field layout. Don’t all sections get a field layout as soon as they’re created?

**Comment by lukeholder** [comment]
A missing volume driver that has been removed after being set up as a volume seems to not return a field layout.
