### ISSUE TITLE
Graphiql fails to initialize

### ISSUE THREAD

**Issue by askogrand** [markhuot/craftql#37]
Running `dev-master` to get around `parentNode` issue on `RC1`, when browsing `/admin/craftql/browse`, I get the following message:

```
TypeError: Cannot read property 'reduce' of null
    at exports.default (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.2/graphiql.min.js:1:556326)
    at buildEnumDef (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.2/graphiql.min.js:1:676391)
    at buildType (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.2/graphiql.min.js:1:674856)
    at getNamedType (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.2/graphiql.min.js:1:673667)
    at https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.2/graphiql.min.js:1:678521
    at Array.map (<anonymous>)
    at exports.buildClientSchema (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.2/graphiql.min.js:1:678482)
    at https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.2/graphiql.min.js:1:46309
    at <anonymous>
```

**Comment by markhuot** [comment]
Looks to be an issue with the schema. Enums are generated for select fields (single or multiple) and asset fields. Are you able to share your database with me (my email is on my profile if you wouldn't mind sending it directly).

**Comment by edolyne** [comment]
@markhuot 

I've got some similar issues:

```
Error: Must be named. Unexpected name: .
    at exports.assertValidName (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.2/graphiql.min.js:1:658437)
    at https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.2/graphiql.min.js:1:606528
    at Array.map (<anonymous>)
    at defineEnumValues (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.2/graphiql.min.js:1:606468)
    at new GraphQLEnumType (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.2/graphiql.min.js:1:614053)
    at buildEnumDef (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.2/graphiql.min.js:1:676258)
    at buildType (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.2/graphiql.min.js:1:674856)
    at getNamedType (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.2/graphiql.min.js:1:673667)
    at https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.2/graphiql.min.js:1:678521
    at Array.map (<anonymous>)
```

I'm able to query, but only something like:

```graphql
{
  entries(section: Journal) {
    id
    title
    
  }
}
```

Going to  `... on Blog {}` is about where things stop, and I also get a No schema available message on Graphiql.  I'll email you a database.

**Comment by markhuot** [comment]
Thanks @edolyne. There's some "magic" going on to convert Craft handles in to GraphQL type names. So I'd like to explore where that's failing in your database to make it a bit more resilient.

**Comment by edolyne** [comment]
@markhuot Sounds like a plan, I just sent it over. Hope it helps shed some light onto where things are failing.

**Comment by markhuot** [comment]
`dev-master` should fix both of these issues. They were related only in that I wasn't properly transforming checkboxes/dropdown values in to GraphQL's more strict naming schemes.

Please let me know if you have any more issues @askogrand and @edolyne!

----

Specific fixes are here: https://github.com/markhuot/craftql/compare/714b3441...df2b2713
