### ISSUE TITLE
InvariantViolation from GraphQL with recent upgrade in release 1.0.0-beta.27 

### ISSUE THREAD

**Issue by zmetcalf** [markhuot/craftql#49]
I am receiving an InvariantViolation from GraphQL. This happened with beta 27 because rolling back to beta 26 fixed it. The admin plugin screen still works but posts from Apollo are not. 

Here is the posted query: 
`{"query":"{\n  entries(section: [jobs], limit: 2) {\n    ... on Jobs {\n      title\n    }\n 
 }\n}\n","operationName":null}`

```
GraphQL\Error\InvariantViolation: Mutation fields must not be empty in /var/www/vendor/webonyx/graphql-php/src/Utils/Utils.php:231
Stack trace:
#0 /var/www/vendor/webonyx/graphql-php/src/Type/Definition/ObjectType.php(222): GraphQL\Utils\Utils::invariant(false, 'Mutation fields...')
#1 /var/www/vendor/webonyx/graphql-php/src/Type/Schema.php(423): GraphQL\Type\Definition\ObjectType->assertValid()
#2 /var/www/vendor/markhuot/craftql/src/Services/GraphQLService.php(97): GraphQL\Type\Schema->assertValid()
#3 /var/www/vendor/markhuot/craftql/src/Controllers/ApiController.php(116): markhuot\CraftQL\Services\GraphQLService->getSchema(Object(markhuot\CraftQL\Models\Token))
#4 [internal function]: markhuot\CraftQL\Controllers\ApiController->actionIndex()
#5 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#6 /var/www/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#7 /var/www/vendor/craftcms/cms/src/web/Controller.php(80): yii\base\Controller->runAction('index', Array)
#8 /var/www/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('index', Array)
#9 /var/www/vendor/craftcms/cms/src/web/Application.php(251): yii\base\Module->runAction('craftql/api/ind...', Array)
#10 /var/www/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('craftql/api/ind...', Array)
#11 /var/www/vendor/craftcms/cms/src/web/Application.php(216): yii\web\Application->handleRequest(Object(craft\web\Request))
#12 /var/www/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#13 /var/www/html/index.php(35): yii\base\Application->run()
#14 {main}
```

**Comment by markhuot** [comment]
Interesting. `dev-master` should fix this up. The issue is if you've disabled all your entry types from mutations, then GraphQL is left with an empty Mutation object, which it doesn't like. For now there's a placeholder `helloWorld` field in there to get around this. Let me know if everything's working well for you on `dev-master` and I'll cut a full release.

**Comment by zmetcalf** [comment]
Worked like a charm, thank you!
